#!/bin/bash
#SBATCH --job-name=chg_HiC_R1_bowtie
#SBATCH --partition=batch
#SBATCH --mail-type=ALL
#SBATCH --mail-user=chg85779@uga.edu
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=24
#SBATCH --mem=100gb
#SBATCH --time=16:00:00
#SBATCH --output=Run123_CHG.%j.out
#SBATCH --error=Run123_CHG.%j.err


bowtie2 --local -x /path/to/indexed/genome.fai -U /path/to/HiC_R1_001.fastq.gz --reorder /path/to/outfile_R1.sam
