#!/bin/bash
#SBATCH --job-name=chg_HiC_R1_bowtie
#SBATCH --partition=batch
#SBATCH --mail-type=ALL
#SBATCH --mail-user=chg85779@uga.edu
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=24
#SBATCH --mem=100gb
#SBATCH --time=16:00:00
#SBATCH --output=Run123_CHG.%j.out
#SBATCH --error=Run123_CHG.%j.err


bowtie2 --local -x /scratch/chg85779/Run123/scaffolds_FINAL.fasta2.fai -U /home/chg85779/Run123/Fastq/123-97_Afum_HiC_S39_R1_001.fastq.gz --reorder /scratch/chg85779/Run123/HiC_CEA10_R1_bowtie_reorder.sam
