#!/bin/bash
#SBATCH --job-name=HiC_build_Matrix
#SBATCH --partition=batch
#SBATCH --mail-type=ALL
#SBATCH --mail-user=chg85779@uga.edu
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=24
#SBATCH --mem=100gb
#SBATCH --time=16:00:00
#SBATCH --output=Run123_CHG.%j.out
#SBATCH --error=Run123_CHG.%j.err

hicBuildMatrix --samFiles /path/to/HiC_R1.bam /path/to/HiC_R2.bam 
--binSize 10000 ###genome represented in 10,000 sections###
--restrictionSequence GATC 
--danglingSequence GATC ###same as restriction sequence since DpnII is used###
--restrictionCutFile /path/to/HiC_restsites.bed 
--threads 12 
-outBam /path/to/outfile.bam ###The bam file is useful to check the quality of the Hi-C library on the genome browser. A good Hi-C library should contain piles of reads near the restriction fragment sites###
--outFileName /path/to/File_HiC_matrix.h5 ### output matrix will be in h5 format ###
--QCfolder /path/to/QC_directory ###make this directory before running script, html file is saved with plots containing useful information for the quality control of the Hi-C sample like the number of valid pairs, duplicated pairs, self-ligations etc###
