#!/bin/bash
#SBATCH --job-name=FindRestSites
#SBATCH --partition=batch
#SBATCH --mail-type=ALL
#SBATCH --mail-user=chg85779@uga.edu
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=24
#SBATCH --mem=100gb
#SBATCH --time=16:00:00
#SBATCH --output=Run123_CHG.%j.out
#SBATCH --error=Run123_CHG.%j.err


### to generate a bed file of restriction sites in the genome; useful for high resolution plots ###
### Proximo fungal kit uses DpnII, target sequence (searchPattern) is GATC ###

hicFindRestSite --fasta /path/to/genome.fna --searchPattern GATC -o /path/to/outfile_HiC_restsites.bed
